// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	Name         string             `json:"name"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	Role         pgtype.Text        `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
